#!/usr/bin/env bash

set -e

FILE_PREFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "${#}" -ne 1 ]]; then
	echo "You must pass exactly ONE file prefix."
	exit 1
fi

echo "${1}"
FILE_SUFFIX="${1}"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${FILE_SUFFIX}${FILE_PREFIX}"
