color0 #494550
color1 #ffb4ab
color2 #cfbcff
color3 #cdc1e6
color4 #ffaeda
color5 #cfbcff
color6 #cdc1e6
color7 #e6e1e8
color8 #948e9b
color9 #ffb4ab
color10 #cfbcff
color11 #cdc1e6
color12 #ffaeda
color13 #cfbcff
color14 #cdc1e6
color15 #e6e1e8

cursor                #e6e1e8
cursor_text_color     #141318
background            #141318
foreground            #e6e1e8
selection_foreground  #cac4d2
selection_background  #494550
active_border_color   #cfbcff
inactive_border_color #494550
url_color             #cfbcff

active_tab_foreground   #37216d
active_tab_background   #cfbcff
inactive_tab_foreground #cac4d2
inactive_tab_background #494550
cursor_trail_color      #cac4d2
