#!/bin/bash

#!/bin/bash
HOME_USER="leotsgo"
WORK_USER="lbermejo"
WORK_EMAIL="lbermejo@pagbank.com"
PERSONAL_EMAIL="me@leotsgo.dev"

git config --global user.name "Leonardo Diniz Bermejo"
git config --global alias.s "!git status -s"
git config --global alias.l "!git log --pretty=format:'%C(blue)%h%C(red)%d %C(white)%s - %C(green)%cn, %C(cyan)%cr'"

case "$USER" in
"$HOME_USER")
	git config --global user.signingkey "AB2C228810A1F5EE"
	git config --global user.email "$PERSONAL_EMAIL"
	git config --global commit.gpgsign true
	;;

"$WORK_USER")
	git config --global user.email "$WORK_EMAIL"
	;;
esac
